#!/bin/bash

mv assembly_racon.fa Final_racon.fa
rm temp_reads_to_draft.paf 

echo "checking assembly quality"
module load user/all/mamba_python_3_6

busco --version

threads="5"

busco --in Final_racon.fa --mode genome --lineage_dataset metazoa_odb10 --cpu $threads --out busco_sponge/
