#!/bin/bash


module load user/all/biomamba

threads="5"

for i in {1..3}; do
	echo "starting polishing round $i"
	minimap2 -x map-ont -t 5 assembly_racon.fa Sponge_all_Long.fastq.gz > temp_reads_to_draft.paf
	racon -t $threads -m 8 -x -6 -g -8 -w 500 Sponge_all_Long.fastq.gz temp_reads_to_draft.paf assembly_racon.fa > temp_draft_new.fa
	mv temp_draft_new.fa assembly_racon.fa
done
